[[HDF4]]
arch = "aarch64"
git-tree-sha1 = "4f5ad07accfb828c43e1c3cb336b15d2fb45bcee"
os = "macos"

    [[HDF4.download]]
    sha256 = "26148b3d552bbad52bc7a4eeecdbe7623b3ae32b2e21b1733dc586b2bda1ddc7"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.aarch64-apple-darwin.tar.gz"
[[HDF4]]
arch = "aarch64"
git-tree-sha1 = "a2b048d8c516a2b0f07b5be14bcd90ce27f0c14d"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "7e18d5ea1392e5fc6427239838ea916e5963cbc3304cef249f992c7f6478e1e2"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.aarch64-linux-gnu.tar.gz"
[[HDF4]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "84f425e275e0eb20547d15a2b83b75ab2a7ca1f9"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "05570a49c44284169765cbb6bc108a07ba70046949e25a0865eb7e616ed1fdf3"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.armv6l-linux-gnueabihf.tar.gz"
[[HDF4]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0eb2e51eecc81817dce049d6a163131e311bc6a1"
libc = "musl"
os = "linux"

    [[HDF4.download]]
    sha256 = "1b749be57d5627d0706e28ab90baac207e2dd1733c2840d6cc5ae915588179ac"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.armv6l-linux-musleabihf.tar.gz"
[[HDF4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "904fda647b095e9f1d2912448fcf581dd33963c7"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "9330ee1e3546d054c5620fdae8a437258ba27b373f03073db76d3c68048973f9"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.armv7l-linux-gnueabihf.tar.gz"
[[HDF4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc12944018fd7d9a8d5af3b1cc39d89f3daf7a4e"
libc = "musl"
os = "linux"

    [[HDF4.download]]
    sha256 = "479d8288d0b6962b5aa7e4c547abdaf67e8eb1d3d0bbd6aff4ed9562c91fc17f"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.armv7l-linux-musleabihf.tar.gz"
[[HDF4]]
arch = "i686"
git-tree-sha1 = "7d4d44682b95aad9c9ff8c4958a88e8ecb9fcd06"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "422c3a4a4ec3c82099a13876e2eef5ccf9c50bc5ef3e9f2ad531c0f58b0d9641"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.i686-linux-gnu.tar.gz"
[[HDF4]]
arch = "i686"
git-tree-sha1 = "b214ac7be36c51dce28fa775dfa9f135715d9e58"
libc = "musl"
os = "linux"

    [[HDF4.download]]
    sha256 = "3c91c55adeb86ebae11961267ade3ea01f03bef4e7d3ef7886abb8482eeb4ddc"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.i686-linux-musl.tar.gz"
[[HDF4]]
arch = "i686"
git-tree-sha1 = "dff6b5f043387caed43bc20c966f867464237f1e"
os = "windows"

    [[HDF4.download]]
    sha256 = "a12c014cf7ac098eaac6525e02c6585cd659f075b4614a4082fe1baed8fc122f"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.i686-w64-mingw32.tar.gz"
[[HDF4]]
arch = "powerpc64le"
git-tree-sha1 = "bc7de273ff2f954a43db628da4aaa1407c5db093"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "a1127067801168ba1f0fbeb282b685b1056906032d92bef0eb95536ff9b0cfec"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.powerpc64le-linux-gnu.tar.gz"
[[HDF4]]
arch = "x86_64"
git-tree-sha1 = "0dab154099e00da54bbfe012457e4563ebfcb9a9"
os = "macos"

    [[HDF4.download]]
    sha256 = "8c39ced9cf34da1ae42da3e217501b1008043eef4ede8c886c9c9c52cda5b2d3"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.x86_64-apple-darwin.tar.gz"
[[HDF4]]
arch = "x86_64"
git-tree-sha1 = "864fa25ec849503ae1f4ae6e0ac2ae33f39d7396"
libc = "glibc"
os = "linux"

    [[HDF4.download]]
    sha256 = "5c410bec60275465a9c091b33734d3f02212912fde038a2cdaf2d4c1c1cb9b16"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.x86_64-linux-gnu.tar.gz"
[[HDF4]]
arch = "x86_64"
git-tree-sha1 = "344f239175f8f041562d5210161d20168f19ecd0"
os = "windows"

    [[HDF4.download]]
    sha256 = "085ac14842fbbfe5684654066b854fb12826a9768efe8d639fb07cfde630b79e"
    url = "https://github.com/JuliaBinaryWrappers/HDF4_jll.jl/releases/download/HDF4-v4.2.16+0/HDF4.v4.2.16.x86_64-w64-mingw32.tar.gz"
