# Autogenerated wrapper script for HDF4_jll for x86_64-w64-mingw32
export hdfed, hdfimport, hdfls, hdiff, hdp, hrepack, libhdf, libmfhdf

using JpegTurbo_jll
using Zlib_jll
using libaec_jll
JLLWrappers.@generate_wrapper_header("HDF4")
JLLWrappers.@declare_library_product(libhdf, "libhdf.dll")
JLLWrappers.@declare_library_product(libmfhdf, "libmfhdf.dll")
JLLWrappers.@declare_executable_product(hdfed)
JLLWrappers.@declare_executable_product(hdfimport)
JLLWrappers.@declare_executable_product(hdfls)
JLLWrappers.@declare_executable_product(hdiff)
JLLWrappers.@declare_executable_product(hdp)
JLLWrappers.@declare_executable_product(hrepack)
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll, Zlib_jll, libaec_jll)
    JLLWrappers.@init_library_product(
        libhdf,
        "bin\\libhdf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmfhdf,
        "bin\\libmfhdf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        hdfed,
        "bin\\hdfed.exe",
    )

    JLLWrappers.@init_executable_product(
        hdfimport,
        "bin\\hdfimport.exe",
    )

    JLLWrappers.@init_executable_product(
        hdfls,
        "bin\\hdfls.exe",
    )

    JLLWrappers.@init_executable_product(
        hdiff,
        "bin\\hdiff.exe",
    )

    JLLWrappers.@init_executable_product(
        hdp,
        "bin\\hdp.exe",
    )

    JLLWrappers.@init_executable_product(
        hrepack,
        "bin\\hrepack.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
